url=https://rezzqa6.its-cs.com/Auth/Login?returnUrl=%2FDashboard
email =itsindiaqa6@gmail.com

password =Netm0an@1
browser=chrome

timeZone= (GMT+00:00) Africa/Monrovia

firstName = Automation

lastName = Test

emailID=c3834717@gmail.com

location =Testing

parentLocation = Root

timeout=20

theme=R&R

language = english (US)

Zoom=100%

RoomName=Testing1 (Testing)

location= Testing

duration=7

Capacity=5

prepration =5

deskname=Desk1 (Testing)

addname=computer1 (Testing)

addID=computer1

defaultduration=6

prepartiontime=6

noshowwaitTime=10

level1Warning=6

level2WarningMessage=7

level3Warning=8

inactivityTimeout=1439

lockTimeout=1439

location=Testing

startTime=15:15

StartTime1 =15:20

StartTime2= 15:25

Pleasechoose=Test Tags2

DeskTags= Chandrika user Tags

RoomTags= Automation

ComputerTags= Computer

Locations= All

UsersTag = Automation Tags

AdminPolicy = All rules

Name = GuestUser

Userprefix = @

Numberoffigure=6

length=7

Character=numeric

userexpiryperiod=hours

NumberofPeriod=1
Activation = on first login 

period= 1 month

BookingType =past

periods=day

context =Tags

UserName =Desktop

Password1 =Chandu.30@

//computers
MaxmiumBookingPerMonth =20

BookingDuration = 5

BookingPerDay =2

BookingAllowedPerDay= 3

MaxmiumPeriodToBookinAdvance= 3

MaxmiumExtendTime =5

NumberofExtension = 3

Maxmiumallowperday=3

Hour=06
Minute=00
endHour=17
endMinute=01

Date From Today (28/08/2026)
Date To  Today (28/08/2026)

customName=test

reserveBookingDate=2026, 9, 24

auth1=MyPC
auth2=Google
auth3=Microsoft
auth4=EntraID
auth5=LibrayLogin
                
Checkbox="showBookingTooltipForOthers"
Checkbox2= showUsername"

Resource="showRoom",
                "showDesk",
                "showPc"
                
                
 sourceuser=Automation Test (c3834717@gmail.com)
 
 SourceRoom=Test (Testing)